include_guard (DIRECTORY)

if (CCL_DISABLE_CPACK)
    return ()
endif ()

set (CPACK_PACKAGE_VENDOR ${ccldemo_COMPANY_NAME})
set (CPACK_DEBIAN_PACKAGE_MAINTAINER ${ccldemo_VENDOR_NAME})
set (CPACK_PACKAGE_CONTACT ${ccldemo_VENDOR_MAIL})
set (CPACK_PACKAGE_NAME "ccldemo")
#set (CPACK_PACKAGE_DESCRIPTION_SUMMARY "Some summary")
set (CPACK_PACKAGE_VERSION_MAJOR ${ccldemo_VERSION_MAJOR})
set (CPACK_PACKAGE_VERSION_MINOR ${ccldemo_VERSION_MINOR})
set (CPACK_PACKAGE_VERSION_PATCH ${ccldemo_VERSION_REVISION})
set (CPACK_PACKAGE_VERSION "${ccldemo_VERSION_MAJOR}.${ccldemo_VERSION_MINOR}.${ccldemo_VERSION_REVISION}.${ccldemo_VERSION_BUILD}")
#set (CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENCE")
#set (CPACK_RESOURCE_FILE_README "${CMAKE_CURRENT_SOURCE_DIR}/README.md")

set (CPACK_GENERATOR "DEB")

set (CPACK_DEBIAN_PACKAGE_SECTION "devel")
set (CPACK_DEBIAN_PACKAGE_HOMEPAGE ${ccldemo_WEBSITE})

set (CPACK_PACKAGE_FILE_NAME "${ccldemo_NAME}-${VENDOR_TARGET_ARCHITECTURE}")

include (CPack)
